### ISSUE TITLE
Generate tests in forEach loop mark first loop with tests as skipped 

### ISSUE THREAD

**Issue by PeaceDate** [Shelex/cypress-allure-plugin#183]
If run test as generated in forEach loop, as Example

```
const appsData = [
    {
        headerSelector: baseSelectors.h1,
        subHeaderSelector: baseSelectors.h2,
        buttonSelector: baseSelectors.button,
        host: 3001
    },
    {
        headerSelector: baseSelectors.h1,
        subHeaderSelector: baseSelectors.h2,
        buttonSelector: baseSelectors.button,
        host:3002
    }
]

appsData.forEach(
    (property: {
        headerSelector: string
        subHeaderSelector: string
        buttonSelector: string,
    }) => {

        describe(`Test suite`, () => {
           context(`Some check`, () => {
               beforeEach(() => {
                  basePage.openLocalhost(host)
              })
               
              it(`Some case`, () => {
                 basePage.checkSomeFeature(property.headerSelector);
                 basePage.checkSomeFeature(property.subHeaderSelector);
                 basePage.checkSomeFeature(property.buttonSelector);
              })
           })
        })
      })
    })
  })
```
These tests, as  in the example it will be two test, will be displays in test report:
First loop will be skipped (but it's passed) <--- That is not good :(
Second will be passed (That is good :) )

What should I do? 

Typescript + Cypress 10.11.0 

Screenshots:

<img width="727" alt="Screenshot 2023-01-26 at 22 02 24" src="https://user-images.githubusercontent.com/55971575/214938436-60ff3239-3fbe-4695-bf5d-1070dd83cdf8.png">

<img width="727" alt="Screenshot 2023-01-26 at 22 02 33" src="https://user-images.githubusercontent.com/55971575/214938578-5f9b859f-b830-48ca-8633-720c234db58b.png">

<img width="1536" alt="Screenshot 2023-01-26 at 22 03 00" src="https://user-images.githubusercontent.com/55971575/214938636-0aa13175-b73b-4d44-9848-c68745d8291d.png">

**Comment by Shelex** [comment]
Does not reproduce for me in latest fix (v2.34.1), where some skipping tests logic was fixed and it may had an impact resulting in this case as well.
If it still - please reopen this issue.

**Comment by PeaceDate** [comment]
@Shelex 
Still reproduce

Test
<img width="1148" alt="Screenshot 2023-02-02 at 21 10 27" src="https://user-images.githubusercontent.com/55971575/216428641-fa289d92-09e5-427a-81d3-11d0370c0c00.png">

 Latest version (v2.34.1)
<img width="354" alt="Screenshot 2023-02-02 at 21 09 46" src="https://user-images.githubusercontent.com/55971575/216428657-885e5bc9-d55e-41eb-8d50-6871c8dbfb81.png">

Result
<img width="1840" alt="Screenshot 2023-02-02 at 21 08 56" src="https://user-images.githubusercontent.com/55971575/216428665-4abd9162-4bf9-4ace-8ac6-4e3923da83f7.png">

**Comment by PeaceDate** [comment]
@Shelex Here more information and ready repo for test [HERE](https://github.com/Shelex/cypress-allure-plugin/issues/188)

**Comment by PeaceDate** [comment]
I've reopened it in new issue
